### PR TITLE
Add more information to the PROCESS_BASIC_INFORMATION struct

### PR DESCRIPTION
**Pull request by FYN-Michiel**
Not sure if this is the correct way to structure this but the extra information provided is very useful

### CODE REVIEW

**Comment by dahall** [comment]
This structure is a port from the C structure defined by the API. Changing the field types will break the APIs with which it is associated.

**Comment by dahall** [comment]
What are you trying to accomplish? There may be another way.

**Comment by FYN-Michiel** [comment]
> What are you trying to accomplish? There may be another way.

At the very least expose the InheritedFromUniqueProcessId value, we already use that currently.
All variables are listed on the Microsoft documentation page.

**Comment by dahall** [comment]
Resolved with properties added to structure. Released in 4.0.1.

**Pull request closed without merging**
