### PR TITLE
Lower System.ValueTuple version dependency.

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by dahall** [comment]
Is the intent to reduce overall dependencies?

**Comment by NN---** [comment]
The intent to use lower version of dependency to prevent the following conflict.
Also it turns out that there are redundant dependencies and having in one place is enough.

https://github.com/theraot/Theraot/issues/182

**Comment by dahall** [comment]
@NN--- With the committed but unreleased changes made to remove older .NET dependencies, the dependency on Threraot is removed. Is this PR still needed?

**Comment by NN---** [comment]
Yes.
It is better to have lower version in any case if possible.

**Comment by NN---** [comment]
Thank you!

**Pull request merged**
