### PR TITLE
Add ContextSwitcher class.

### PR DESCRIPTION
**Pull request by NN---**
#209

### CODE REVIEW

**Comment by dahall** [comment]
I added a CoClass attribute to the IContextCallback so that you can `new` it directly.
```cs
var contextCallback = new IContextCallback();
```

Do you think anyone would use a helper class on this that would have methods to add COM objects and then automatically release them all on `Dispose()`?

**Comment by dahall** [comment]
Something like:
```cs
public class ComContext : IDisposable
{
   private IContextCallback ctx;
   private List<(Type, object, CLSCTX, REGCLS)> regs = new List<(Type, object, CLSCTX, REGCLS)>();
   public ComContext() => ctx = new IContextCallback();

   public void Register<T>(T obj, CLSCTX clsCtx, REGCLS flags) => regs.Add(typeof(T), obj, clsCtx, flags);
   public void Dispose() => Disconnect();
   public void Connect() => ctx.ContextCallback(EnterCallback, default, IID_ContextCallback, 5);
   public void Disconnect() => ctx.ContextCallback(DisconnectCallback, default, IID_ContextCallback, 5);
   private HRESULT EnterCallback(in ComCallData data)
   {
      foreach (var i in regs)
         CoRegisterClassObj(i.....)
   }
   private HRESULT DisconnectCallback(in ComCallData data)
   {
      foreach (var i in regs)
         CoRevokeClassObj(i.....)
      return CoDisconnectContext(timout);
   }
}
```

**Comment by NN---** [comment]
Don’t know whether anyone needs a helper class.
In fact this feature is a little bit esoteric , not so documented and used mainly in internal implementations.
There is a wrapper for it in CsWinRT: https://github.com/microsoft/CsWinRT/blob/cfbc973fd48453d53311706a3f4a9b8730c762c6/src/WinRT.Runtime/Interop/IContextCallback.cs

**Comment by NN---** [comment]
Thanks for such fast response.

**Pull request merged**
