### PR TITLE
DNS_QUERY_OPTIONS are uint.

### PR DESCRIPTION
**Pull request by NN---**
`  DWORD       Options,`

https://docs.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsquery_w

### CODE REVIEW

**Comment by NN---** [comment]
Fixes #137

**Comment by dahall** [comment]
I accepted this, but I'm going to change it back. While a `DWORD` in [DnsQuery](https://docs.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsquery_w), it is a `ULONG64` in both structures ([`DNS_QUERY_REQUEST`](https://docs.microsoft.com/en-us/windows/win32/api/windns/ns-windns-dns_query_request) and [`MDNS_QUERY_REQUEST`](https://docs.microsoft.com/en-us/windows/win32/api/windns/ns-windns-mdns_query_request)) that use it. Since structure sizing is very picky, and since parameter passing is not (stack pointer so DWORD and ULONG64 are the same), then it needs to stay 64 bits.

**Comment by NN---** [comment]
You cannot change the function prototype.
The WinAPI function must be declared with uint .
Otherwise you pass arguments incorrectly in 32-bit.

**Comment by NN---** [comment]
You can run test in 32-bit and see it is working and once you change DnsQuery to receive ulong it stops working.

**Comment by NN---** [comment]
This breaks DnsApiTests in 32-bit.
I agree there is an inconsistency in the WinAPI itself.

If you look in options documentation you can see it is never bigger than 32-bit.
I think you can simply preserve `uint` and just add padding of another uint.

https://docs.microsoft.com/en-us/windows/win32/api/windns/nf-windns-dnsquery_w
```cpp
DNS_STATUS DnsQuery_W(
  PCWSTR      pszName,
  WORD        wType,
  DWORD       Options,
  PVOID       pExtra,
  PDNS_RECORD *ppQueryResults,
  PVOID       *pReserved
);
```


```cpp
typedef struct _DNS_QUERY_REQUEST {
  ULONG                         Version;
  PCWSTR                        QueryName;
  WORD                          QueryType;
  ULONG64                       QueryOptions;
  PDNS_ADDR_ARRAY               pDnsServerList;
  ULONG                         InterfaceIndex;
  PDNS_QUERY_COMPLETION_ROUTINE pQueryCompletionCallback;
  PVOID                         pQueryContext;
} DNS_QUERY_REQUEST, *PDNS_QUERY_REQUEST;
```


```cpp
typedef struct _MDNS_QUERY_REQUEST {
  ULONG                Version;
  ULONG                ulRefCount;
  PCWSTR               Query;
  WORD                 QueryType;
  ULONG64              QueryOptions;
  ULONG                InterfaceIndex;
  PMDNS_QUERY_CALLBACK pQueryCallback;
  PVOID                pQueryContext;
  BOOL                 fAnswerReceived;
  ULONG                ulResendCount;
} MDNS_QUERY_REQUEST, *PMDNS_QUERY_REQUEST;
```

**Pull request merged**
