### PR TITLE
Correct alignment for WTSINFO and WTSINFOEX.

### LINKED ISSUE #278: Structure member alignment issues in WTSApi32
**Describe the bug**
The timestamp fields in the `WTSINFO` and `WTSINFOEX_LEVEL1` end up with bad values because their offsets within the structure aren't correct. This is due to the `SizeConst = USERNAME_LENGTH + 1` of the previous field in `WTSINFO` messing up the padding. I haven't fiddled with `WTSINFOEX_LEVEL1` but I believe it has similar issues.

Changing `WTSINFO` to use `SizeConst = USERNAME_LENGTH + 2` or adding a `private char _padding` field after `UserName` fixes it.

**What code is involved**
`PInvoke\WTSApi32\WTSApi32.cs`

**Expected behavior**
The timestamp fields should have either 0s or sane values. The `CurrentTime` field should always be sane.

**Repro**
```
if (WTSEnumerateSessionsEx(HWTSSERVER.WTS_CURRENT_SERVER_HANDLE, out var sessionList)) {
    foreach (var session in sessionList) {
        if (WTSQuerySessionInformation(HWTSSERVER.WTS_CURRENT_SERVER_HANDLE, session.SessionId, WTS_INFO_CLASS.WTSSessionInfo, out var pSessionInfo, out var bytesReturned)) {
            using (pSessionInfo) {
                var sessionInfo = pSessionInfo.ToStructure<WTSINFO>(bytesReturned);
                Console.WriteLine("CurrentTime is {0}", sessionInfo.CurrentTime.ToDateTime());
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by NN---**
Fix #278

### CODE REVIEW

**Review by rosenqui-cysiv — APPROVED** [review]
Looks good, and I like that the `FILETIME` extensions aren't needed to get `DateTime` values.

**Comment by dahall** [comment]
I have two comments. First, purely replacing the FILETIME fields with Int64 fields doesn't fix the original #278 issue. The LARGE_INTEGER values are, in fact, FILETIME equivalents. Secondly, changing the type breaks any dependent code. So, I'm trying to understand the need for this PR. It seems to do more harm than good. On @rosenqui-cysiv comment regarding needing extensions, they are included in the Vanara.PInvoke.Shared assembly, so they are already in your build. You are merely referencing their namespace so there is no cost other than a `using` statement.

**Comment by rosenqui-cysiv** [comment]
Bad wording on my part; I didn't mean that one had to write extensions, just that one had to use them (via `using Vanara.Extensions`) in order to get to a `DateTime`.

I believe `LARGE_INTEGER` causes different field alignment due to its `LONGLONG QuadPart` union member. That forces it to an 8-byte boundary vs. 4-byte for `FILETIME`. Switching to use a C# `long` has the same effect and is a lot easier to use.

As for breaking any dependent code, there can't be much out there since it wasn't working the way it was. At best you would get a garbage date, but more often than not it caused an exception.

**Comment by NN---** [comment]
It does work for me.
FILETIME doesn't have the same memory representation as LARGE_INTEGER.
It can be changed to something else but the type is not correct.
Take a look on the WTSINFO definition in MSDN.

**Comment by NN---** [comment]
@dahall Did you try reproducing the issue ?
Thanks for merge.

**Comment by dahall** [comment]
Your original issue, yes. This new one, I did in my test harness, but I'd left the new +2 length to UserName. It worked with `long` values and UserName len + 1.

**Pull request merged**
